name: vexilla_client
description: A Dart client for the Vexilla Feature Flag System.
version: 0.0.2
homepage: https://vexilla.github.io

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  http: ^0.13.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
